image: gitpod/workspace-java-17

tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - Pivotal.vscode-boot-dev-pack
    - redhat.java
    - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test

ports:
  - port: 5050
    visibility: public
  - port: 5432
    visibility: public
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3100
    visibility: public
