
image: gitpod/workspace-java-17

tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - richardwillis.vscode-gradle
