
image: gitpod/workspace-java-21

tasks:
  - init: ./gradlew build -x test

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - vscjava.vscode-gradle

ports:
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 8000
    visibility: public
    onOpen: open-browser
  - port: 5050
    visibility: public
    onOpen: open-browser
  - port: 9411
    visibility: public
    onOpen: open-browser
  - port: 9090
    visibility: public
    onOpen: open-browser
  - port: 3000
    visibility: public
    onOpen: open-browser
