
image: gitpod/workspace-java-17

tasks:
  - init: ./gradlew build -x test

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - richardwillis.vscode-gradle
    - Pivotal.vscode-spring-boot

ports:
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 5050
    visibility: public
    onOpen: open-browser
