
image: gitpod/workspace-java-17

tasks:
  - init: ./gradlew build

ports:
  - port: 5050
    visibility: public
  - port: 5432
    visibility: public
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3100
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - Pivotal.vscode-boot-dev-pack
