version: "3.8"

services:
  postgresqldb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mfscreener
    ports:
      - "5432:5432"
    networks:
      - mfscreener-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - mfscreener-network

networks:
  mfscreener-network:
    driver: bridge

volumes:
  db-data:
