version: 2.1
orbs:
  gradle: circleci/gradle@4.0.0
executors:
  machine_executor_amd64:
    docker:
      - image: ubuntu-2404:current
      - image: cimg/openjdk:25.0
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
jobs:
  gradle_integration_test:
    executor: machine_executor_amd64
    steps:
      - checkout # Checkout your source code
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}
            - gradle-cache-v1-
      - run:
          name: Run Gradle Integration Test
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-v1-{{ checksum "build.gradle" }}
workflows:
  gradle_test:
    jobs:
      - gradle/test:
          executor: machine_executor_amd64
      - gradle_integration_test


