version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - gradle/setup-cache
      - gradle/restore-cache
      - gradle/run:
          command: "./gradlew build"
      - gradle/save-cache

workflows:
  build:
    jobs:
      - build
