version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:21.0.0'
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
jobs:
  gradle_integration_test:
    # executor: machine_executor_amd64
    executor: jdk
    steps:
      - checkout # Checkout your source code
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}
            - gradle-cache-v1-
      - run:
          name: Run Gradle Integration Test
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-v1-{{ checksum "build.gradle" }}
workflows:
  gradle_test:
    jobs:
      - gradle/test:
          executor: jdk
      - gradle_integration_test
