version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  machine_executor_amd64:
    machine:
      image: cimg/openjdk:17.0
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

jobs:
  build:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run: java --version
      - gradle/build:
          gradle-version: '8.0.2'
          java-version: 17

workflows:
  gradle_test:
    jobs:
      - build
