version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/app
    steps:
      - checkout
      - run: mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew build --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Copy build artifacts
          command: cp build/libs/*.jar /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
          destination: artifacts
workflows:
  version: 2
  build:
    jobs:
      - build
