version: '3.8'
services:

  postgresqldb:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    networks:
      - mfscreener-network

  pgadmin:
    image: dpage/pgadmin4
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      postgresqldb:
        condition: service_started
    networks:
      - mfscreener-network


networks:
  mfscreener-network:
    driver: bridge