package com.learning.mfscreener.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import liquibase.Liquibase;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.exception.LiquibaseException;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

@Testcontainers
class MigrationDataIntegrityIT {
    @Container
    static PostgreSQLContainer postgres = new PostgreSQLContainer(DockerImageName.parse("postgres:18.6-alpine"));

    @Test
    void migratesExistingDataWithoutRoundingOrKeyCollisions() throws Exception {
        try (Connection connection = connect()) {
            execute(
                    connection,
                    "CREATE TABLE mf_scheme (scheme_id bigint PRIMARY KEY, scheme_name text NOT NULL, version smallint, created_date timestamp, last_modified_date timestamp)",
                    "CREATE TABLE mf_scheme_nav (id bigint PRIMARY KEY, nav double precision, nav_date date, mf_scheme_id bigint, created_date timestamp, last_modified_date timestamp, CONSTRAINT uc_mf_scheme_nav UNIQUE (nav, nav_date, mf_scheme_id))",
                    "CREATE TABLE mf_scheme_types (scheme_type_id integer PRIMARY KEY, version smallint, created_date timestamp, last_modified_date timestamp)",
                    "CREATE TABLE user_scheme_details (id bigint PRIMARY KEY, version smallint)",
                    "CREATE TABLE user_transaction_details (id bigint PRIMARY KEY, amount double precision, units double precision, nav double precision, balance double precision)",
                    "CREATE TABLE user_cas_details (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
                    "CREATE TABLE user_folio_details (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
                    "CREATE SEQUENCE user_cas_details_seq START WITH 1 INCREMENT BY 50",
                    "CREATE SEQUENCE user_folio_details_seq START WITH 1 INCREMENT BY 50",
                    "INSERT INTO mf_scheme (scheme_id, scheme_name, created_date) VALUES (1, 'Alpha- Growth', '2020-01-01 12:00:00')",
                    "INSERT INTO mf_scheme_nav (id, nav, nav_date, mf_scheme_id) VALUES (10, 11, '2020-01-01', 1), (11, 12, '2020-01-01', 1)",
                    "INSERT INTO user_cas_details (id) VALUES (125)");
        }

        migrate("07-numeric-monetary-columns.xml", false);
        try (Connection connection = connect()) {
            execute(connection, "INSERT INTO user_transaction_details (id, units) VALUES (1, 1.123456789)");
            assertThat(decimal(connection, "SELECT units FROM user_transaction_details WHERE id = 1"))
                    .isEqualByComparingTo(new BigDecimal("1.123456789"));
            assertThat(number(connection, "SELECT id FROM mf_scheme_nav WHERE nav_date = '2020-01-01'"))
                    .isEqualTo(11);
        }

        assertThatThrownBy(() -> migrate("08-timestamptz-alignment.xml", false))
                .isInstanceOf(LiquibaseException.class)
                .hasMessageContaining("Confirm legacy audit timestamps are UTC");
        migrate("08-timestamptz-alignment.xml", true);
        try (Connection connection = connect()) {
            assertThat(
                            bool(
                                    connection,
                                    "SELECT created_date = TIMESTAMPTZ '2020-01-01 12:00:00+00' FROM mf_scheme WHERE scheme_id = 1"))
                    .isTrue();
        }

        migrate("10-version-and-sequences.xml", false);
        try (Connection connection = connect()) {
            assertThat(number(connection, "INSERT INTO user_cas_details DEFAULT VALUES RETURNING id"))
                    .isEqualTo(175);
            assertThat(number(connection, "INSERT INTO user_folio_details DEFAULT VALUES RETURNING id"))
                    .isEqualTo(1);
        }

        migrate("11-trigram-search-indexes.xml", false);
        try (Connection connection = connect()) {
            assertThat(bool(connection, "SELECT to_regclass('idx_mf_scheme_name_unspaced_upper') IS NULL"))
                    .isTrue();
            String expression = string(
                    connection,
                    "SELECT pg_get_expr(indexprs, indrelid) FROM pg_index WHERE indexrelid = 'idx_mf_scheme_name_trgm'::regclass");
            assertThat(expression)
                    .containsIgnoringCase("upper(")
                    .containsIgnoringCase("replace(")
                    .contains("'- '");
        }
    }

    private static void migrate(String file, boolean utcConfirmed) throws Exception {
        try (Connection connection = connect()) {
            execute(connection, "SET TIME ZONE 'America/Los_Angeles'");
            var database =
                    DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
            try (Liquibase liquibase =
                    new Liquibase("db/changelog/migration/" + file, new ClassLoaderResourceAccessor(), database)) {
                if (utcConfirmed) {
                    liquibase.setChangeLogParameter("legacyAuditTimestampsAreUtc", "true");
                }
                liquibase.update();
            }
        }
    }

    private static Connection connect() throws SQLException {
        return DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
    }

    private static void execute(Connection connection, String... statements) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.execute(sql);
            }
        }
    }

    private static long number(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery(sql)) {
            assertThat(result.next()).isTrue();
            return result.getLong(1);
        }
    }

    private static boolean bool(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery(sql)) {
            assertThat(result.next()).isTrue();
            return result.getBoolean(1);
        }
    }

    private static BigDecimal decimal(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery(sql)) {
            assertThat(result.next()).isTrue();
            return result.getBigDecimal(1);
        }
    }

    private static String string(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery(sql)) {
            assertThat(result.next()).isTrue();
            return result.getString(1);
        }
    }
}
